
angular.module('personApp',['ui.router','ngResource','personApp.controllers','personApp.services']);

angular.module('personApp').config(function($stateProvider,$httpProvider){
    $stateProvider.state('persons',{
        url:'/persons',
        templateUrl:'partials/persons.html',
        controller:'PersonListController'
    }).state('viewPerson',{
       url:'/persons/:id/view',
       templateUrl:'partials/person-view.html',
       controller:'PersonViewController'
    }).state('newPerson',{
        url:'/persons/new',
        templateUrl:'partials/person-add.html',
        controller:'PersonCreateController'
    }).state('editPerson',{
        url:'/persons/:id/edit',
        templateUrl:'partials/person-edit.html',
        controller:'PersonEditController'
    }).state('hobbies',{
        url:'/hobbies',
        templateUrl:'partials/hobbies.html',
        controller:'HobbyListController'
    }).state('newHobby',{
        url:'/hobbies/new',
        templateUrl:'partials/hobby-add.html',
        controller:'HobbyCreateController'
    });
}).run(function($state){
   $state.go('persons');
});